apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service-deployment
  namespace: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: 246325869534.dkr.ecr.us-east-1.amazonaws.com/analytics-service:sha-f525ae03576b
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "20m"
            limits:
              memory: "128Mi"
              cpu: "35m"
          ports:
            - containerPort: 8005
          env:
            - name: OTEL_SERVICE_NAME
              value: analytics-service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.namespace=analytics-service
            - name: OTEL_EXPORTER_OTLP_HEADERS
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secret
                  key: OTEL_EXPORTER_OTLP_HEADERS
          envFrom:
            - secretRef:
                name: analytics-service-secret
          startupProbe:
            httpGet: { path: /health, port: 8005 }
            periodSeconds: 5
            failureThreshold: 6
